MWSE/MWSE

MWSE/xSpellList.cpp
Fixed the missing spellType return for xGetSpellList.
=> Fixed the missing spellType return.

readme.md
=> Added a link to the nightly to readme.md

misc/package/Data Files/MWSE/lua/mwse_init.lua
Simple but useful function to remap a value from one scale to another.
```
local x = 13 --13%
x = math.remap(x, 0, 100, -1, 1)
--x should be -0.74
```
=> Added math.remap

docs/source/installation.rst, docs/source/lua/event/enterFrame.rst, docs/source/lua/event/load.rst, docs/source/lua/event/loaded.rst, docs/source/lua/event/save.rst, docs/source/lua/event/saved.rst, docs/source/lua/event/simulate.rst
Also resolves issue #29 by noting that MGE XE 0.10.0 is needed for nightly MWSE.
=> Added enterFrame and simulate event documentation.

docs/source/lua/event/key.rst, docs/source/lua/event/load.rst, docs/source/lua/event/save.rst, docs/source/lua/guide/scancodes.rst
Adds documentation for the 'key' event, including scan codes table.
Corrects filtering information on the save and load event docs.
=> Additional docs

docs/source/lua/event/equip.rst, docs/source/lua/event/equipped.rst, docs/source/lua/event/key.rst, docs/source/lua/event/unequipped.rst
Added first pass for equip, equipped, and unequipped events.
=> Fixed key event documentation and example, + new events

docs/source/lua/event/projectileExpire.rst, docs/source/lua/event/projectileHitActor.rst
=> Added projectileExpire and projectileHitActor event docs.

MWSE/TES3InventoryLua.cpp, docs/source/lua/event/initialized.rst, docs/source/lua/event/load.rst, docs/source/lua/event/loaded.rst
Added first draft docs for initialized event.
Corrected text on load/loaded events.
Fixed incorrect operator that prevented accessing requirements.
=> Added first draft docs for initialized event & fixed requirements.

MWSE/LuaEvents.cpp, MWSE/LuaEvents.h, MWSE/LuaManager.cpp, MWSE/LuaUtil.cpp, MWSE/MemoryUtil.cpp, MWSE/TES3MagicSourceInstance.h, MWSE/TES3MagicSourceInstanceLua.cpp, docs/source/lua/event/magicCast.rst, docs/source/lua/event/spellCast.rst, docs/source/lua/event/spellCastFailure.rst
Adds magicCast, spellCast and spellCastFailure events, and a refactor of a few hook patches.
Still needs code review and testing.
=> Magic cast/failure lua events

MWSE/MWSE.vcxproj, MWSE/MWSE.vcxproj.filters, MWSE/TES3Weapon.cpp, MWSE/TES3Weapon.h, MWSE/TES3WeaponLua.cpp, docs/source/lua/type/tes3/weapon.rst
=> Added and exposed Weapon::isTwoHanded, isRanged, and isAmmo.

misc/package/Data Files/MWSE/core/modConfig/main.lua
Also changes text color to use the palette.
=> Added border to the initial MCM page.

MWSE/LuaManager.cpp, MWSE/LuaManager.h, MWSE/TES3DataHandler.cpp, MWSE/TES3UtilLua.cpp, misc/package/Data Files/MWSE/core/tes3/init.lua
Also fixed some comments.
> NullCascade: Well if things get wonky let me know. May need to call 0x41BE90 (thiscall) with TES3::Game and 0 as params.
=> Binding for tes3.loadGame.

MWSE/TES3UIManager.cpp
Just waiting on feedback before merge.
=> Added initial UIIDs for MenuEnchantment (don't merge)

MWSE/LuaManager.cpp, MWSE/TES3UtilLua.cpp
Patched ui_reenableMenuDialog to leave menu mode if there's no dialog menu.
=> Added tes3.showRepairServiceMenu()

MWSE/LuaTimer.cpp
- followup of the previous fix, did not notice the shift of the timing
value with an internal clock
=> timer - resume fix

MWSE/TES3UtilLua.cpp, autocomplete/definitions/global/tes3/rayTest.lua, docs/source/lua/api/tes3/rayTest.rst
Added optional parameters to rayTest
1. root (Node *) defaults to TES3::Game::get()->worldRoot
2. ignoreSkinned (boolean) defaults to false. When true results will not have any skinned data.
=> New rayTest parameters

MWSE/NITriShapeLua.cpp
Followed vertices inclusion, added normals to NiTriShapeLua
=> Added access to normals in NiTriShapeLua

MWSE/LuaDetectSneakEvent.cpp, MWSE/LuaDetectSneakEvent.h, MWSE/LuaDisableableEventManager.cpp, MWSE/LuaManager.cpp, MWSE/MWSE.vcxproj, MWSE/MWSE.vcxproj.filters, MWSE/TES3MobController.cpp, MWSE/TES3MobController.h, MWSE/TES3MobControllerLua.cpp, MWSE/TES3MobControllerLua.h, MWSE/TES3UtilLua.cpp, autocomplete/definitions/events/standard/detectSneak.lua
Adds a new lua event, `detectSneak`, which triggers whenever an actor attempts to detect another actor sneaking. 
Resolves issue #252 .
=> Add sneak detection event.

MWSE/LuaManager.cpp, MWSE/TES3UIMenuController.h
=> Improve implementation of ReenableMenuDialogue. Resolves #267

MWSE/LuaDisableableEventManager.cpp, MWSE/LuaManager.cpp, MWSE/LuaPostInfoResponseEvent.cpp, MWSE/LuaPostInfoResponseEvent.h, MWSE/MWSE.vcxproj, MWSE/MWSE.vcxproj.filters, autocomplete/definitions/events/standard/postInfoResponse.lua, docs/source/lua/event/postInfoResponse.rst
Adds a new lua event that triggers immediately after a dialogue response is processed.
=> Add postInfoResponse event.

MWSE/LuaManager.cpp
Patch magic effect saving and loading to properly handle custom effects with summons or bound items.
=> Patch magic effect saving and loading

autocomplete/definitions/global/tes3/messageBox.lua
This updates tes3.messageBox autocomplete file with recent changes.
=> Update tes3.messageBox autocomplete

autocomplete/definitions/events/standard/damage.lua, autocomplete/definitions/events/standard/damage/changeFallDamage.lua, autocomplete/definitions/events/standard/damaged.lua, autocomplete/definitions/events/standard/damaged/knockDownCheck.lua, autocomplete/definitions/global/tes3/playSound.lua, autocomplete/definitions/global/timer/game.lua, autocomplete/definitions/global/timer/simulate.lua
Add examples of how to use damaged and damage events. Credits for checking player race go to Null
=> Damage(d) events example

autocomplete/definitions/namedTypes/tes3sound.lua, autocomplete/definitions/namedTypes/tes3sound/__tojson.lua, autocomplete/definitions/namedTypes/tes3sound/filename.lua, autocomplete/definitions/namedTypes/tes3sound/id.lua, autocomplete/definitions/namedTypes/tes3sound/isPlaying.lua, autocomplete/definitions/namedTypes/tes3sound/play.lua, autocomplete/definitions/namedTypes/tes3sound/stop.lua, autocomplete/definitions/namedTypes/tes3sound/volume.lua, autocomplete/definitions/namedTypes/tes3soundGenerator.lua, autocomplete/definitions/namedTypes/tes3soundGenerator/__tojson.lua, autocomplete/definitions/namedTypes/tes3soundGenerator/id.lua, autocomplete/definitions/namedTypes/tes3soundGenerator/sound.lua, autocomplete/definitions/namedTypes/tes3soundGenerator/type.lua
Added tes3sound and tes3soundGenerator to docs.
Which description should be for tes3sound, tes3soundGenerator and filename?
=> docs-tes3sound(Generator)

autocomplete/definitions/events/standard/enterFrame.lua, autocomplete/definitions/events/standard/simulate.lua, autocomplete/definitions/global/timer/simulate.lua
* update-docs for timer.simulate, simulate and enterFrame events based on discussion on Discord, with clean commit history this time!
=> Timers update

autocomplete/definitions/global/timer/delayOneFrame.lua, autocomplete/definitions/global/timer/start.lua
Description for timer type. Copy-pasted callback description from timer.start to timer.delayOneFrame
=> our-favourite-function-docs

autocomplete/definitions/global/table/empty.lua, autocomplete/definitions/global/table/transverse/tableTransverse.lua, autocomplete/definitions/global/table/traverse.lua
Many thanks to @Greatness7 for coming up with example for table.transverse
=> Add missing functions to table api docs

autocomplete/definitions/global/tes3/magicSchoolSkill.lua, autocomplete/definitions/global/tes3/magicSchoolSkill/convertMagicSchoolToSkill.lua
Is this the right way to document this?
=> Add tes3.magicSchoolSkill to the docs

misc/package/Data Files/MWSE/core/mwse_init.lua
If any of these changes are controversial I can revert
=> Rename arguments for some functions in table api to mach with their docs

docs/event-definitions-guide.md, docs/function-definitions-guide.md, docs/readme.md, docs/type-definitions-guide.md
Added 3 guides on how to write event, function, and named types definition files.
=> Docs contributions guide

MWSE/LuaCalcBlockChanceEvent.cpp, MWSE/LuaCalcBlockChanceEvent.h, MWSE/LuaDisableableEventManager.cpp, MWSE/LuaManager.cpp, MWSE/MWSE.vcxproj, MWSE/MWSE.vcxproj.filters, autocomplete/definitions/events/standard/calcBlockChance.lua, docs/source/events/calcBlockChance.md, misc/package/Data Files/MWSE/core/lib/tes3/event.lua, misc/package/Data Files/MWSE/core/meta/event/calcBlockChance.lua, misc/package/Data Files/MWSE/core/meta/lib/event.lua
This introduces the calcBlockChance event, docs included.
Is this alright for merging?
=> Calc block chance event

misc/package/Data Files/MWSE/core/lib/ltn12.lua
This should silence the last of the warnings that can pop up in MWSE's release.
=> Silence the warnings in ltn12.lua

MWSE/TES3UIManager.cpp
Covers MenuInventory, MenuContents, MenuBarter, and the cursor (when picking up/moving items)
=> Add itemTile related UIIDS.

misc/package/Data Files/MWSE/core/lib/unitwind/init.lua, misc/package/Data Files/MWSE/core/lib/unitwind/tests.lua, misc/package/Data Files/MWSE/core/lib/unitwind/validator.lua
- **Fast**: Can be configured to run immediately, then close Morrowind once the tests have completed. Run hundreds of tests in a matter of seconds for rapid development/debugging
- **Logging**: Jest-style logging makes it really easy to see which tests failed and why
- **Assertions**: Works with standard lua assertions, or using the easy-to-read unitwind `expects` syntax, e.g `unitwind:expects(1).NOT.toBe(2)`
- **Mocking** support: easily mock out any data structure or api, allowing you to run tests instantly that would otherwise have to wait for data to be initialised
```lua
local UnitWind = require("unitwind")
local unitwind = UnitWind.new{
enabled = true,
highlight = true,
exitAfter = true,
}
unitwind:start("Test Suite")
unitwind:test("Test toBe", function()
unitwind:expect(1).toBe(1) …
```
=> Add unit testing framework UnitWind, with examples/tests

MWSE/TES3Skill.cpp, MWSE/TES3Skill.h, MWSE/TES3SkillLua.cpp, autocomplete/definitions/namedTypes/tes3skill/description.lua, docs/source/types/tes3skill.md, misc/package/Data Files/MWSE/core/meta/class/tes3skill.lua
Seems to work, just copying from the existing description stuff for classes/races, etc.
=> Expose skill descriptions

CSSE/WindowMain.cpp
Before and after of the change.
=> CSSE: Increase the width of the statusbar sections.

MWSE/TES3UtilLua.cpp, autocomplete/definitions/global/tes3/setExpelled.lua, docs/source/apis/tes3.md, misc/package/Data Files/MWSE/core/meta/lib/tes3.lua
Usage:
```lua
tes3.setExpelled({
faction = tes3.getFaction("Mages Guild"),
})
```
=> Add `tes3.setExpelled`

MWSE/TES3MobileActor.cpp, MWSE/TES3MobileActor.h, MWSE/TES3MobileActorLua.h, MWSE/TES3MobileObject.h, autocomplete/definitions/namedTypes/tes3mobileActor/isSliding.lua, docs/source/types/tes3mobileActor.md, docs/source/types/tes3mobileCreature.md, docs/source/types/tes3mobileNPC.md, docs/source/types/tes3mobilePlayer.md, misc/package/Data Files/MWSE/core/meta/class/tes3mobileActor.lua
Based on what I posted recently on our discord server.
=> Implement tes3mobileActor.isSliding

docs/source/references/magic-effects-modded.md
I tried to insert them into the right spot in the list, but let me know it should be changed. Also let me know if I should edit another file in addition to this one.
=> Add custom effect ids for "fortifty magicka regeneration" mod

docs/source/guides/mod-config.md
This PR updates the documentation of the MCM guide to reflect some of the recent changes to the API.
This is still a rough draft, but I wanted to share it as is in case people have feedback on the structure/suggestions about the content.
=> Update MCM Guide

CSSE/MetadataUtil.cpp
Requested by Rakanishu on our Discord channel.
=> CSSE: make deprecated asset check case-insensitive

MWSE/TES3MobileActor.cpp, MWSE/TES3MobileActor.h, MWSE/TES3MobileActorLua.h, autocomplete/definitions/namedTypes/tes3mobileActor/isSpeaking.lua, docs/source/types/tes3mobileActor.md, docs/source/types/tes3mobileCreature.md, docs/source/types/tes3mobileNPC.md, docs/source/types/tes3mobilePlayer.md, misc/package/Data Files/MWSE/core/meta/class/tes3mobileActor.lua
It checks `lipsyncLevel != -1` on the mobile's animation data.
Axemagister requested this on our Discord channel.
=> Add tes3mobileActor.isSpeaking

autocomplete/definitions/global/mwse/registerModConfig.lua, docs/source/apis/mwse.md, misc/package/Data Files/MWSE/core/mcm/components/templates/Template.lua, misc/package/Data Files/MWSE/core/mcm/main.lua, misc/package/Data Files/MWSE/core/meta/lib/mwse.lua
=> Store templates for registered menus

autocomplete/definitions/global/mwse/registerModConfig.lua, docs/source/apis/mwse.md, misc/package/Data Files/MWSE/core/mcm/components/templates/Template.lua, misc/package/Data Files/MWSE/core/mcm/main.lua, misc/package/Data Files/MWSE/core/meta/lib/mwse.lua
=> Revert "Store templates for registered menus"
