- MWSE/ScriptUtil.cpp
- MWSE/ScriptUtil.h
- MWSE/ScriptUtilLua.cpp
All tested and working, but I didn't have anything to refer to as far as 0 arg functions, so maybe I'm messing up state somewhere by not having any reference passed.
> Added mwscript.getPCSneaking, getPCRunning, and getPCJumping.

- MWSE/TES3Faction.cpp
- MWSE/TES3Faction.h
- MWSE/TES3FactionLua.cpp
- docs/source/lua/type/tes3/baseObject/objectType.rst
- misc/package/Data Files/MWSE/lua/mwse/tes3/objectType.lua
Exposes playerRank, playerReputation, playerJoined, and playerExpelled for factions.
Adds and documents tes3.objectType.faction.
> Faction stuff

- MWSE/LuaEvents.cpp
- MWSE/LuaEvents.h
- MWSE/LuaManager.cpp
- MWSE/MWSE.vcxproj
- MWSE/MWSE.vcxproj.filters
- MWSE/NIDefines.h
- MWSE/NIObjectLua.cpp
- MWSE/NIObjectNET.cpp
- MWSE/NIObjectNET.h
- MWSE/NITimeController.h
- MWSE/NITimeControllerLua.cpp
- MWSE/NITimeControllerLua.h
- MWSE/TES3Actor.cpp
- MWSE/TES3MobController.cpp
- MWSE/TES3MobController.h
- MWSE/TES3Reference.cpp
- MWSE/TES3Reference.h
- docs/source/lua/event/mobileActivated.rst
- docs/source/lua/event/mobileDeactivated.rst
- docs/source/lua/event/weaponReadied.rst
- docs/source/lua/event/weaponUnreadied.rst
Contains the following things:
- `mobileAttached` and `mobileDetached` events for when a mobile actor comes and goes.
- `weaponReadied` and `weaponUnreadied` events for when a weapon is not just equipped, but actively wielded.
- Fixes for `reference.position = value`.
- Changes `equipped` and `unequipped` events to not fire if there's no associated mobile actor/reference.
Still needs:
> Branch for weapon sheathing feature requests

- MWSE-Update/AutoUpdater.cs
MWSE-Update no longer overwrites resources (anything in data files apart from data files/mwse) unless using the -overwriteResources flag. This is helpful for updating installs using menu texture replacements that overwrite the mcm texture.
> MWSE-Update no longer overwrites resources

- MWSE/TES3PlayerAnimationData.h
- MWSE/TES3UtilLua.cpp
Add tes3.getPlayerEyePosition() and tes3.getPlayerEyeVector() functions.
Usage test:
```
event.register("simulate", function()
if tes3.is3rdPerson() then tes3.player.sceneNode.appCulled = true end
local eyepos = tes3.getPlayerEyePosition()
local eyevec = tes3.getPlayerEyeVector()
local rayhit = tes3.rayTest{position=eyepos, direction=eyevec}
if rayhit then
tes3.messageBox("%s", rayhit.reference)
end
if tes3.is3rdPerson() then tes3.player.sceneNode.appCulled = false end
end)
```
The messagebox should accurately match the native targeting mechanic. This differs from raycasting with getCameraPosition/getCameraVector, which have undesired behavior when in 3rd person or using the vanity camera.
> Add getPlayerEyePosition and getPlayerEyeVector.

- misc/package/Data Files/MWSE/core/mcm/main.lua
When in game, closing MCM with escape key closes both MCM and the main menu.
> escape key closes MCM

- MWSE/TES3Faction.cpp
- MWSE/TES3Faction.h
- MWSE/TES3FactionLua.cpp
Possible fix for #221
The id property inherited from BaseObject erroneously gave the
faction's name instead of its id.  This overrides that property
with one directly returning the id from the Faction struct.
However, this is just a band-aid fix, and may not be desired as
it appears to be correcting Vanilla functionality.
> Override tes3faction.id in lua to give id

- MWSE/MWSE.vcxproj
- deps/boost/Dep_Boost/Dep_Boost.vcxproj
- deps/boost/boost/functional/hash/extensions.hpp
- deps/boost/boost/functional/hash/hash.hpp
- deps/boost/boost/regex/v4/match_results.hpp
- upgrade toolset from v141 to v142
- specified c++17 standard for both mwse and boost_dep projects
- adapted some stuff in boost_dep to support c++17
- enabled multi processor compilation to speed up the build for both
mwse and boost_dep
> using c++17 standard

- MWSE/LuaTimer.cpp
- fixed the state of a resumed timer. Otherwise, while attempting to
cancel it, it is searched in the wrong container
> timer controller

- MWSE/LuaManager.cpp
- removed one OnPCEquip hooks when called from
TES3_ui_inventory_equipInventoryItemToPlayer. It caused the "equip"
event to fire twice when using quickslots
> hook removal

- MWSE/TES3MagicEffect.cpp
- MWSE/TES3MagicEffect.h
- MWSE/TES3MagicEffectController.cpp
- MWSE/TES3MagicEffectLua.cpp
- MWSE/TES3UtilLua.cpp
dynamic spell effect description
- used tes3 allocation / deallocation primitive to prevent access violations
- patched code called while populating enchanting and spellmaking menus to prevent spell effect description reset. Therefore spell descriptions can be changed at anytime. No leak has been observed in the MagicEffectController.
- NullCascade, this is my very first patch, should I have missed something or done crappy stuff, I'd appreciate you teach me quickly how things could have been done in a better way : Meta Barj0#4864
> Magic effect description

- MWSE/LuaObject.cpp
- MWSE/LuaObject.h
- MWSE/TES3Enchantment.cpp
- MWSE/TES3Enchantment.h
- MWSE/TES3EnchantmentLua.cpp
- autocomplete/definitions/namedTypes/tes3enchantment/create.lua
- autocomplete/definitions/namedTypes/tes3enchantment/create/description.rst
- added tes3enchantment.create and extended the tes3.createObject
binding counterpart
- id parameter for object creation (all handled types) is now optional
> tes3enchantment.create binding

- MWSE/LuaObject.h
- tes3.createObject and their tes3*.create counterparts now throw
exception is a mesh path longer than 31 characters is specified
> binding fixes

- MWSE/LuaManager.cpp
The event is triggered too soon, before levelUpProgress and levelupsPerAttribute are updated. Instead, trigger the event when the UI updates, just after levelupsPerAttribute is updated.
> Add a better hook for skill trained (skillRaised) event.

- MWSE/TES3MagicEffect.cpp
- MWSE/TES3MagicEffect.h
- MWSE/TES3MagicEffectLua.cpp
- fix the 'description' property. Perhaps due to sol3 migration, it
worked improperly with a getter on a field and a setter on a method.
Now, getter and setter are methods.
> MagicEffect binding

- MWSE/LuaManager.cpp
Avoid using the pointer in esi until after checking for a custom effect.
> Fix potential crash with vanilla effects.

- misc/package/Data Files/MWSE/core/lib/logging/colors.lua
- misc/package/Data Files/MWSE/core/lib/logging/logger.lua
Adds two new logging libraries to `core/lib`
Taken straight from https://github.com/kikito/ansicolors.lua, allows for color manipulation of console text.
The MWSE Logger allows you to register a logger for your mod.
* Mod-specific log levels
* Log levels can be controlled with MCM settings
* Log messages color coded according to log level
* Optional setting to print messages to a separate log file
> Add logger and ansicolors libraries

- MWSE/MWSEConfig.cpp
- MWSE/MWSEConfig.h
- docs/source/guides/logging.md
- misc/package/Data Files/MWSE/core/MWSE MCM/i18n/eng.lua
- misc/package/Data Files/MWSE/core/MWSE MCM/main.lua
- misc/package/Data Files/MWSE/core/lib/logging/logger.lua
Added Logging Guide to the Docs
Made EnableLogColors a global setting, with a new setting in the MWSE MCM. This is set to false by default, so users will not get weird characters in their MWSE.log file.
Please confirm I didn't miss anything adding the new setting to MWSEConfig.cpp, or when adding the new doc page.
> Add docs and make log color setting global

- autocomplete/definitions/global/tes3/isKeyEqual.lua
- docs/source/apis/tes3.md
- misc/package/Data Files/MWSE/core/lib/tes3/init.lua
- misc/package/Data Files/MWSE/core/meta/lib/tes3.lua
Adds a new function, `tes3.isKeyEqual` to compare to key objects. Includes updated document files for autocomplete and website docs.
> Add tes3.isKeyEqual

- MWSE/LuaManager.cpp
- MWSE/MWSE.vcxproj
- MWSE/MWSE.vcxproj.filters
- MWSE/NIDefines.h
- MWSE/NIQuaternion.cpp
- MWSE/NIQuaternion.h
- MWSE/NIQuaternionLua.cpp
- MWSE/NIQuaternionLua.h
- MWSE/TES3Vectors.cpp
- MWSE/TES3Vectors.h
- MWSE/TES3VectorsLua.cpp
- autocomplete/definitions/namedTypes/niQuaternion.lua
- autocomplete/definitions/namedTypes/niQuaternion/copy.lua
- autocomplete/definitions/namedTypes/niQuaternion/fromAxisAngle.lua
- autocomplete/definitions/namedTypes/niQuaternion/fromRotation.lua
- autocomplete/definitions/namedTypes/niQuaternion/slerp.lua
- autocomplete/definitions/namedTypes/niQuaternion/toAxisAngle.lua
- autocomplete/definitions/namedTypes/niQuaternion/toRotation.lua
- autocomplete/definitions/namedTypes/niQuaternion/w.lua
- autocomplete/definitions/namedTypes/niQuaternion/x.lua
- autocomplete/definitions/namedTypes/niQuaternion/y.lua
- autocomplete/definitions/namedTypes/niQuaternion/z.lua
- autocomplete/definitions/namedTypes/tes3matrix33/fromQuaternion.lua
- autocomplete/definitions/namedTypes/tes3matrix33/toQuaternion.lua
- docs/source/types/niQuaternion.md
- docs/source/types/tes3matrix33.md
- misc/package/Data Files/MWSE/core/meta/class/niQuaternion.lua
- misc/package/Data Files/MWSE/core/meta/class/tes3matrix33.lua
Adds bindings to `NiQuaternion` and exposes a few methods to lua. Also adds some convenience methods to `TES3::Matrix33` for converting to/from quaternions.
> Add NiQuaternion bindings.

- autocomplete/builders/emmy.lua
- misc/package/Data Files/MWSE/core/meta/lib/lpeg.lua
- misc/package/Data Files/MWSE/core/meta/lib/re.lua
- misc/package/Data Files/MWSE/core/meta/lib/table.lua
- misc/package/Data Files/MWSE/core/meta/lib/tes3.lua
- misc/package/Data Files/MWSE/core/meta/lib/tes3ui.lua
- misc/package/Data Files/MWSE/core/meta/lib/timer.lua
Due to an error in emmy.lua, the links in the popups in VS Code were pointing to the wrong place.
> Fix example links

- autocomplete/definitions/global/event/isRegistered.lua
- docs/source/apis/event.md
- misc/package/Data Files/MWSE/core/lib/event.lua
- misc/package/Data Files/MWSE/core/meta/lib/event.lua
This adds an isRegistered function to event.lua. There currently is no way to check for that besides storing that state in your own script. You might want to register an event at multiple locations and need to check if it already exists. Is this fine to merge?
> Add event.isRegistered

- misc/package/Data Files/MWSE/core/mwse_init.lua
- Added a new shallow version of `table.copymissing`
- This will be used instead of recursive one when loading config
This change is warranted by the fact that copying stuff recursively borks loading configs that include tables. This is particularly glaring when using MCM's `exclusionsPage`, where any removal of a k-v pair that otherwise exists in the default config table is treated as an error. It shouldn't be so.
> Fix config load gotchas

- misc/package/Data Files/MWSE/core/mcm/components/pages/ExclusionsPage.lua
This will prevent the removed default entries in the exclusionsPage from reappearing on each call of the `mwse.loadConfig`. 
Before, this usually occurred when the game was restarted and the mod's mcm was opened again. The `mwse.loadConfig` would fill in the missing values in the table from the ones in `defaultConfig`, which made the entries in the exclusionsPage removed by the user in the last game run reappear.
An alternative to #387, but this one doesn't require the mods using exclusionsPage to change any of their code to make their pages work. On the other hand, this one makes all the explicitly disabled entries end up in the mod's configuration `.json` file.
> Fix issue with exclusionsPage

- autocomplete/definitions/global/mwscript/stopScript.lua
- autocomplete/definitions/global/tes3/get3rdPersonCameraOffset.lua
- autocomplete/definitions/global/tes3/set3rdPersonCameraOffset.lua
- autocomplete/definitions/namedTypes/tes3bodyPartManager/setBodyPartForObject.lua
- docs/source/apis/mwscript.md
- docs/source/apis/tes3.md
- docs/source/references/other/ni-class-hierarchy.md
- docs/source/types/tes3bodyPartManager.md
- misc/package/Data Files/MWSE/core/meta/class/tes3bodyPartManager.lua
- misc/package/Data Files/MWSE/core/meta/lib/mwscript.lua
- misc/package/Data Files/MWSE/core/meta/lib/tes3.lua
I'd like some feedback:
1. Which classes should I remove? Some only exist in newer versions of Gamebryo so they aren't relevant for Morrowind, some exist in Morrowind but they aren't present in MWSE's code, while some are present in MWSE, but aren't yet exposed to Lua scripting. I'd prefer to leave all the classes supported by Morrowind be they exposed to Lua/MWSE or not.
2. I mostly followed the grouping as in the official documentation, so I also put some classes which we use in place of NI classes such as tes3matrix33. What are your opinions on that?
3. Any other thoughts or suggestions?
Please ignore the first commit, it wasn't meant to end in this PR.
I might organize this into a Mermaid diagram once we settle on how this should look like. That's why I have an example of such a …
> Add a reference page on NI classes hierarchy

- docs/source/guides/logging.md
- misc/package/Data Files/MWSE/core/lib/logging/logger.lua
Usage example:
```Lua
local logger = require("logging.logger")
local log = logger.new{
name = "Test Mod",
logLevel = "TRACE",
-- Make all the logged messages also be logged to the in-game console
logToConsole = true,
}
log:trace("This is a trace message")
log:debug("This is a debug message")
log:info("This is an info message")
log:warn("This is a warn message")
log:error("This is an error message")
-- Changing the logToConsole setting later:
log.logToConsole = false
-- No logging messages will be printed to the in-game console after this point
log:setLogLevel("INFO")
```
> Add an option to log to console to lua logger API

- misc/package/Data Files/MWSE/core/mwse/ui/api/showMessageMenu.lua
`customBlock` lets you add whatever you want to the tes3.showMessageMenu, in between the header and the message.
> Add customBlock param to tes3.showMessageMenu

- .github/workflows/deploy-documentation.yml
- docs/mkdocs.yml
Adds them by using the [plugin suggested by MkDocs](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-dates).
For available date types you can look at the mkdocs-git-revision-date-localized-plugin's [docs](https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/). I'll list the ones supported by Material for MkDocs here:
```
November 28, 2019           # type: date (default)
November 28, 2019 13:57:28  # type: datetime
2019-11-28                  # type: iso_date
2019-11-28 13:57:26         # type: iso_datetime
20 hours ago                # type: timeago
```
I decided to use `datetime`, and I set `enable_creation_date: true`, so also the date the page was first created is also shown.
> Docs: add revision date to the pages

- autocomplete/definitions/namedTypes/mwseLogger/includeTimestamp.lua
- docs/source/guides/logging.md
- docs/source/types/mwseLogger.md
- misc/package/Data Files/MWSE/core/lib/logging/logger.lua
- misc/package/Data Files/MWSE/core/meta/class/mwseLogger.lua
```lua
local logger = MWSELogger.new{
name = string.format("JoyOfPainting - %s", serviceName),
logLevel = config.mcm.logLevel,
includeTimestamp = true,
}
```
```
[01:04:36.988] [JoyOfPainting - main: DEBUG] Initialising Interops
```
> Mwselogger timestamp

- autocomplete/definitions/global/json/decode.lua
- autocomplete/definitions/global/json/encode.lua
- autocomplete/definitions/global/json/loadfile.lua
- autocomplete/definitions/global/mwse/loadConfig.lua
- docs/source/apis/json.md
- docs/source/apis/mwse.md
- misc/package/Data Files/MWSE/core/initialize.lua
- misc/package/Data Files/MWSE/core/meta/lib/json.lua
- misc/package/Data Files/MWSE/core/meta/lib/mwse.lua
This is my attempt at resolving an issue people usually stumble upon when using `mwse.loadConfig()`. 
If the `defaults` table is given, then loop through checking if a key k in the `defaults` table is a `number` and if there exists an entry in the loaded config table with key `tostring(k)`. If such a key exists, convert it to an integer.
> Convert string keys to integers in mwse.loadConfig

- misc/package/Data Files/MWSE/core/mcm/components/settings/Dropdown.lua
This fixes a problem that previously caused scrolling to not update length when using mcm Dropdown in Mod Config.
In particular, if there was a dropdown at the bottom of the page, items could not be selected, but this will now be available.
Previous: expanding logging level but cannot scroll.
PR: can scroll.
> Update parent scrolling when Dropdown is expanded or collapsed

- misc/package/Data Files/MWSE/core/mcm/components/Component.lua
- misc/package/Data Files/MWSE/core/mcm/components/categories/Category.lua
- misc/package/Data Files/MWSE/core/mcm/components/infos/Info.lua
- misc/package/Data Files/MWSE/core/mcm/components/pages/ExclusionsPage.lua
- misc/package/Data Files/MWSE/core/mcm/components/pages/FilterPage.lua
- misc/package/Data Files/MWSE/core/mcm/components/pages/MouseOverPage.lua
- misc/package/Data Files/MWSE/core/mcm/components/settings/Dropdown.lua
- misc/package/Data Files/MWSE/core/mcm/components/settings/KeyBinder.lua
- misc/package/Data Files/MWSE/core/mcm/components/templates/Template.lua
- misc/package/Data Files/MWSE/core/mcm/mcm.lua
- misc/package/Data Files/MWSE/core/mcm/variables/GlobalBoolean.lua
- misc/package/Data Files/MWSE/core/mcm/variables/PlayerData.lua
In short, use more standard library functions where possible, reduce nesting, and use tes3uiElement:getTopLevelMenu instead of deprecated getTopLevelParent, since that causes Lua Language Server to produce warnings.
> Small MCM refactoring

- MWSE/LuaManager.cpp
- misc/package/Data Files/MWSE/core/lib/dependencyManagement/DependencyManager.lua
- misc/package/Data Files/MWSE/core/lib/dependencyManagement/DependencyNotifier.lua
- misc/package/Data Files/MWSE/core/lib/dependencyManagement/types/mods.lua
- misc/package/Data Files/MWSE/core/lib/dependencyManagement/util.lua
- misc/package/Data Files/MWSE/core/mwse/dependencies/main.lua
- misc/package/Data Files/MWSE/core/startLuaMods.lua
Brief summary of changes:
1. Fix improper getting of package name in `startLuaMods.lua`
2. Refactoring. Use more standard functions we have. Made filename check case insensitive (based on https://github.com/MWSE/MWSE/commit/ecf4c61081ee9a4b2c62b094279432df719aff92).
Moved `mwse.getConfig("EnableDependencyChecks")` from `mwse\dependencies\main.lua` to `DependencyManager`. The package dependencies are checked twice: first from `execLuaMod` in `startLuaMods.lua`, then from `mwse\dependencies\main.lua`.  Previously, there was no `mwse.getConfig("EnableDependencyChecks")` check in  `startLuaMods.lua`.
3. Mod's plugin can be disabled in the launcher. Don't check dependencies for mods with disabled plugins (based on https://github.com/MWSE/MWSE/commit/aa646c5cbc6215dcc6a043da1403d1ff63ab4f53)
4. …
> DependencyManager updates

- MWSE/TES3UtilLua.cpp
Item pickup/down sounds are played for the player. In my opinion, it makes more sense to play the Up sound when an item gets added to the player's inventory since that sound is played when the player picks up items from the game world. The opposite is true for dropping an item. That's my reasoning for making the switch.
Also, I added a `mobile == playerMobile` check in `tes3.removeItem`.
> Switch pickup sounds for `tes3.addItem`, `tes3.removeItem` and `tes3.transferItem`

- MWSE/TES3ActorAnimationController.cpp
From the context in the file, it looks like the `setOpacity` should accept values in the [0.0 - 1.0] range. So, clamp the values to the right range.
> Fix tes3actorAnimationController:updateOpacity

- misc/package/Data Files/MWSE/core/mcm/components/pages/ExclusionsPage.lua
Large exclusion lists caused a lot of lag when clicking "toggle filtered", because it was deleting and recreating each element one at a time. This has been changed to simply update the underlying data then recreate the whole page.
> Improve performance of ExclusionsPage toggleFiltered

- misc/package/Data Files/MWSE/core/mwse/ui/tes3uiElement/createTextInput.lua
i did this by changing the `preTextInputKeyPress` event.
if the `numeric` flag is set and a number wasn't entered, it checks whether that character is "." or "-". then:
- "-"  is allowed iff it's the first character entered.
- "." is allowed iff it's the first time "." was pressed.
> fixed bug where numeric TextInputFields wouldn't allow negative or decimal numbers

- .gitattributes
i changed `.gitattributes` to enable CRLF conversion for `.md` and `.lua` files. without this, git freaks out when rebuilding docs on non-windows operating systems.
> added CRLF conversions for .lua and .md files

- misc/package/Data Files/MWSE/core/mcm/components/settings/KeyBinder.lua
as it is now, `mwseCombo` supports multiple prefixes being used, but the UI only displays one. (so if a keybind has shift and alt held, only "Alt - key" will be shown.) this small change allows multiple prefixes to be shown (e.g. "Shift - Alt- key".)
only a few select lines of code were changed
> added support for multiple key prefixes in the `mwseKeyCombo` display string

- autocomplete/builders/mkdocs.lua
- docs/source/apis/mwse.mcm.md
- docs/source/apis/mwse.md
- docs/source/apis/table.md
- docs/source/types/mwseMCMConfigVariable.md
- docs/source/types/mwseMCMCustomVariable.md
- docs/source/types/mwseMCMGlobal.md
- docs/source/types/mwseMCMPlayerData.md
- docs/source/types/mwseMCMSettingNewVariable.md
- docs/source/types/mwseMCMTableVariable.md
- docs/source/types/mwseMCMVariable.md
one line of code was changed: it has to do with how parameters are detected in the `mkdocs` autobuilder. documentation was also rebuilt
the problem is caused by `builders/mkdocs.lua:217`, which reads:
```lua
local name, type = paramStr:match("([%w]+)[:]?[%s]?(.*)")
```
the pattern for getting the `name` of a function argument, i.e. `([%w]+)`, only matches alphanumeric characters. this currently causes a problem for functions with variadic arguments, as seen in the newly created [`table.map` documentation](https://mwse.github.io/MWSE/apis/table/#tablemap). 
without the changes introduced in this PR, the documentation generated for the `f` parameter of `table.map` is:
```lua
f (fun(k: unknown, v: unknown, nil))
```
when it should read 
```lua
f (fun(k: unknown, v: unknown, ...))
```
another …
> minor bug-fix: `mkdocs` incorrectly generates documentation for arguments that are functions

- autocomplete/builders/emmy.lua
- autocomplete/definitions/namedTypes/mwseMCMSlider/convertToLabelValue/DistanceSlider.lua
- autocomplete/definitions/namedTypes/mwseMCMSlider/convertToLabelValue/SkillSlider.lua
- autocomplete/definitions/namedTypes/mwseMCMSlider/new.lua
- docs/source/apis/mwse.mcm.md
- docs/source/types/mwseMCMCategory.md
- docs/source/types/mwseMCMDecimalSlider.md
- docs/source/types/mwseMCMExclusionsPage.md
- docs/source/types/mwseMCMFilterPage.md
- docs/source/types/mwseMCMMouseOverPage.md
- docs/source/types/mwseMCMPage.md
- docs/source/types/mwseMCMPercentageSlider.md
- docs/source/types/mwseMCMSideBarPage.md
- docs/source/types/mwseMCMSideBySideBlock.md
- docs/source/types/mwseMCMSlider.md
- misc/package/Data Files/MWSE/core/meta/class/mwseMCMCategory.lua
- misc/package/Data Files/MWSE/core/meta/class/mwseMCMSlider.lua
- misc/package/Data Files/MWSE/core/meta/lib/mwse/mcm.lua
this PR fixes two bugs:
the first is pretty minor: there was a typo in the examples for `convertToLabelValue`. i wrote `convertToValueLabel` instead of `convertToLabelValue`. 😞 
the second is a bit more involved: the `emmy.lua` autobuilder was not properly handling optional parameters that are functions. i first noticed this problem with `convertToLabelValue`, since it has `optional = true`, but the generated `meta` file does not list the parameter as optional. the problem is that the type for `convertToLabelValue` is getting generated as
```lua
fun(self: mwseMCMDecimalSlider, variableValue: number): number|nil|string
```
when it should be 
```lua
nil|fun(self: mwseMCMDecimalSlider, variableValue: number): number|string
```
(i.e., the `nil` is getting added to the return value of the …
> fixed documentation bug (in autobuilder and `autocomplete/definitions`)

- docs/source/guides/metadata.md
- misc/package/Data Files/MWSE/core/lib/dependencyManagement/DependencyManager.lua
this is my attempt to fix a documentation bug that NullCascade mentioned on discord a week or so ago.
the metadata guide says to use `load-order`, but the `startLuaMods.lua` file only cares about a `load-priority` key. i updated the documentation to reflect this.
> fixed `load-priority` documentation bug

- autocomplete/definitions/global/json/decode.lua
- autocomplete/definitions/global/json/encode.lua
- autocomplete/definitions/global/json/loadfile.lua
- autocomplete/definitions/global/json/savefile.lua
- autocomplete/definitions/global/mwse/saveConfig.lua
- autocomplete/definitions/global/string/split.lua
- autocomplete/definitions/global/table/filter.lua
- autocomplete/definitions/global/table/filterarray.lua
- autocomplete/definitions/global/table/map.lua
- autocomplete/definitions/global/tes3/addSoulGem.lua
- autocomplete/definitions/global/tes3/getLuaModMetadata.lua
- autocomplete/definitions/global/tes3/payMerchant.lua
- docs/source/apis/json.md
- docs/source/apis/mwse.md
- docs/source/apis/string.md
- docs/source/apis/table.md
- docs/source/apis/tes3.md
- docs/source/guides/metadata.md
- misc/package/Data Files/MWSE/core/meta/lib/json.lua
- misc/package/Data Files/MWSE/core/meta/lib/mwse.lua
- misc/package/Data Files/MWSE/core/meta/lib/string.lua
- misc/package/Data Files/MWSE/core/meta/lib/table.lua
- misc/package/Data Files/MWSE/core/meta/lib/tes3.lua
i reworded the documentation in a few places, added some more detail here and there, and fixed/tweaked the function parameters/return types for some functions.
i'd be happy to undo some changes (or revise them) if people would like
the documentation was also rebuilt
* i changed the return type of `tes3.getLuaModMetadata` to be `MWSE.Metadata`. however, this is only defined in `core/lib/dependencyManagement/DependencyManager.lua`, so there's no link to it in the generated `mkdocs` documentation. but it's still useful for code completion in visual studio.
* i can add the `MWSE.Metadata` class to the `autocomplete` folder if people think that would be appropriate
> minor documentation changes

- autocomplete/definitions/events/standard/lockPick.lua
- autocomplete/definitions/events/standard/trapDisarm.lua
- autocomplete/definitions/namedTypes/tes3skill/id.lua
- docs/source/events/lockPick.md
- docs/source/events/trapDisarm.md
- docs/source/types/tes3skill.md
- misc/package/Data Files/MWSE/core/meta/class/tes3skill.lua
- misc/package/Data Files/MWSE/core/meta/event/lockPick.lua
- misc/package/Data Files/MWSE/core/meta/event/trapDisarm.lua
Here's a summary of the things being fixed:
1. The `trapDisarm` and `lockPick` events incorrectly say the `chance` parameter is "Read only". This is evidenced by lines  `747` and `807` of the `TES3Reference.cpp` file (within the `attemptUnlockDisarm` function). I also did some testing in-game and was able to update the chances using these events.
2. The `id` field of the `tes3skill` object incorrectly lists that `id` is a `string`, when it should be a `tes3.skill`.
Documentation has been rebuilt.
> fixed documentation: `trapDisarm`, `lockpick` events; `tes3skill` object

- misc/package/Data Files/MWSE/core/mcm/components/Component.lua
This makes the cause clearer than it currently is: #506. We already errored out in this case, but the logged error message mentioned line 18 in `mcm.components.Component.lua` which wasn't quite clear that the user shouldn't call this before "modConfigReady" triggered.
> MCM: Error out if using a MCM component before `modConfigReady`

- autocomplete/definitions/global/mwse/mcm/createTableVariable.lua
- autocomplete/definitions/namedTypes/mwseMCMTableVariable/id.lua
- autocomplete/definitions/namedTypes/mwseMCMTableVariable/new.lua
- docs/source/apis/mwse.mcm.md
- docs/source/types/mwseMCMTableVariable.md
- misc/package/Data Files/MWSE/core/meta/class/mwseMCMTableVariable.lua
- misc/package/Data Files/MWSE/core/meta/lib/mwse/mcm.lua
the documentation says the `id` field of a `TableVariable` must be a `string`, but the `mcm` code allows for it to be a `number`
documentation has been rebuilt
> docs fix: allow `MCMTableVariable.id` to be a `number`

- autocomplete/definitions/global/tes3/getKeyName.lua
- docs/source/apis/tes3.md
- misc/package/Data Files/MWSE/core/mcm/components/settings/KeyBinder.lua
- misc/package/Data Files/MWSE/core/meta/lib/tes3.lua
- misc/package/Data Files/MWSE/core/mwse/tes3/getKeyName/main.lua
- `tes3.getKeyName(keyCode)` will take in a `tes3.scanCode` and return its name, as defined by the relevant GMST. 
- For example, `tes3.getKeyName(tes3.scanCode.p) == "P"`.
- I haven't made any documentation files yet, but would be happy to do so if people are interested in merging this PR.
- I also changed `mwseMCMKeyBinder:getLetter` to make it use `tes3.getKeyName`. This should make it more consistent with the in-game controls menu. (Although I'd be happy to revert this part if people would like.)
This function works as follows:
0. The user-facing names for scan codes are specified in the `sKeyName_X` GMSTs, where `X` is a 0-padded hexadecimal number (i.e.,  `07` instead of `7`).
1. Given a `tes3.scanCode`, the `id` of the relevant GMST (taking 0-padding into account) is given by …
> Add `tes3.getKeyName(keyCode)` function

- autocomplete/definitions/global/timer.lua
- autocomplete/definitions/global/timer/start.lua
- docs/source/apis/timer.md
- docs/source/guides/timers.md
- misc/package/Data Files/MWSE/core/meta/lib/timer.lua
These warnings were added at the top of the `Timers` guide, the top of the `timer` API page, and in the description of the `timer.start` function.
> Documentation: warn about timers getting canceled before `loaded` event

- misc/package/Data Files/MWSE/core/mcm/main.lua
I did some rudimentary testing and everything seems to work fine, but a bit more testing may be required. The changes were fairly minimal.
- This was implemented by triggering making the `mouseOver` and `mouseLeave` events for the `modNameButton` and `modEntryBlock` trigger the corresponding events for the `imageButton`.
- I had to register events to both `modNameButton` and `modEntryBlock` so that the icon would show when hovering over the mod label and when hovering over the whitespace in between the mod label and the favorites icon.
> Make mcm icon visible when hovering over mod label

- misc/package/Data Files/MWSE/core/mcm/components/pages/SideBarPage.lua
In three different parts of the `SideBarPage.lua` file, the `Component:getComponent` function was used to create a new instance of a class. This PR replaces each call to `Component:getComponent` with the constructor of the relevant class.
Each of those calls to `getComponent(self, data)` would ultimately result in the following lines of code being executed:
```lua
data.parentComponent = self
... -- complicated logic to fetch `componentClass`
return componentClass:new(data)
```
Since `componentClass` is already known ahead of time, it's possible to replace `getComponent(self, data)` with `componentClass:new(data)`. The only other difference is that instead of writing `data.class = className`, we write `data.parentComponent = self`.
Here are some consequences of these changes:
- In my …
> Reduce usage of `getComponent` in `SideBarPage.lua`

- misc/package/Data Files/MWSE/core/mcm/fileUtils.lua
Previously, the `create` methods were case-insensitive.
The lua code dump suggests that only two mods ever made use of this functionality: "Brutal Backstabbing" and "Better Sorting Names". And both those mods only utilized the case-insensitivity to call `mwse.mcm.createtemplate` instead of `mwse.mcm.createTemplate`. This change adds backwards compatibility for those mods.
This is done by saying that the path of the `template` class is equal to the path of the `Template` class. This results in a `createtemplate` function being generated. (This is similar to how `createHyperLink` is supported by piggybacking off of `createHyperlink`.)
> Support `mwse.mcm.createtemplate`

- autocomplete/definitions/namedTypes/mwseMCMDropdown/convertToLabelValue.lua
- docs/source/types/mwseMCMDropdown.md
- misc/package/Data Files/MWSE/core/mcm/components/settings/Dropdown.lua
- misc/package/Data Files/MWSE/core/meta/class/mwseMCMDropdown.lua
Previously, `Dropdown` inherited the default implementation of `convertToLabelValue`. This basically resulted in `option.value` being returned instead of `option.label`. This change seeks to remedy that.
This change makes `Dropdown:convertToLabelValue(variableValue)` find the first `option` with `option.value == variableValue`, and then it returns `option.label`.
> Add `Dropdown:convertToLabelValue`

- autocomplete/builders/common.lua
- autocomplete/builders/emmy.lua
- autocomplete/builders/mkdocs.lua
I added a few different annotation types to `common.lua`, `mkdocs.lua`, and `emmy.lua`.
I also made a few minor code formatting changes, to help with readability. But I tried to keep those changes minimal. I can walk back any/all of those changes if desired.
I also added some comments with some insights I gained from adding annotations, and those may suggest future changes.
After making these changes, I was able to rebuild the documentation with no errors and no changes.
> Add annotations to `builders`, and make minor formatting changes

- misc/package/Data Files/MWSE/core/mcm/components/settings/Dropdown.lua
Before this fix, the description of a `mwseMCMDropdown` would only be shown when hovering over its label. When hovering over the `thinBorder` that houses the currently selected option, the description of the parent component would be shown, instead of the description of the `Dropdown` element.
This change makes the description be shown when hovering over the `thinBorder` element. It also allows the description to be shown when selecting an option (when the dropdown menu is active).
> Bug fix: show `Dropdown.description` when hovering over options

- misc/package/Data Files/MWSE/core/mcm/components/Component.lua
- misc/package/Data Files/MWSE/core/mcm/components/infos/MouseOverInfo.lua
- misc/package/Data Files/MWSE/core/mcm/components/pages/SideBarPage.lua
The most recent commit caused a bunch of log spam:
```
'getMouseOverText' (a nil value)
stack traceback:
.\Data Files\MWSE\core\lib\event.lua:328: in function 'getMouseOverText'
...a Files\MWSE\core\mcm\components\infos\mouseoverinfo.lua:24: in function 'updateInfo'
...a Files\MWSE\core\mcm\components\infos\mouseoverinfo.lua:35: in function <...a Files\MWSE\core\mcm\components\infos\mouseoverinfo.lua:34>
```
This was happening because the `MCM:MouseOver` event was structured so that the `eventData` was either a `mwseMCMComponent`, or an empty `table`. This clashes with the `eventData` structure of every event. 
And it led to problems here because the `MouseOverInfo:updateInfo` method was being called on the `eventData` (which sometimes doubled as a `component`. In particular, the `nil` …
> Hotfix for log spam caused by latest commit

- misc/package/Data Files/MWSE/core/mcm/main.lua
A mod with title of (e.g.) "Pete's Itinerant Intervention" will add a newline in the MCM even though it fits on one line, which annoyingly goes away as soon as you hover the scrollview.
Fixes that.
> Update MCM layout an extra time to shake out unnecessary newlines.

- docs/source/guides/storing-data.md
There is a misspelled word in the phrase "be that across save sessions" in the second sentence. This is corrected.
In the last sentence of the paragraph I have made the grammar clearer, and moved the interrupting parenthetical to the end of the sentence.
> Correct misspelling in opening paragraph and clarify ending sentince therein.

- MWSE/TES3UIManager.cpp
Closes #564.
Didn't go overboard on the subelements.
> Add new UIIDs for MenuPersuasion.

- autocomplete/definitions/namedTypes/tes3uiElement/reorder.lua
- docs/source/types/tes3uiElement.md
- misc/package/Data Files/MWSE/core/meta/class/tes3uiElement.lua
This marks `before` and `after` as optional since only one of them is required.
> Fix docs for `tes3uiElement:reorder`

- autocomplete/definitions/namedTypes/mwseMCMSlider/new.lua
- docs/source/types/mwseMCMSlider.md
- misc/package/Data Files/MWSE/core/mcm/components/settings/Slider.lua
- misc/package/Data Files/MWSE/core/meta/class/mwseMCMSlider.lua
This PR makes two changes:
1. The `label` field is now marked as required in the documentation for the `mwseMCMSlider` constructor. This is because the default implementation of `Slider:updateValueLabel()` triggers an error if `self.label == nil`.
2. The `assert` statements were removed from the `mwseMCMSlider` constructor. The checks are still performed but will now log warning messages instead. This should hopefully result in fewer unnecessary softlocks in people's mods.
> MCM Slider: Remove `assert`s from constructor, update documentation

- autocomplete/definitions/global/table/contains.lua
- autocomplete/definitions/global/table/equal.lua
- autocomplete/definitions/global/table/equals.lua
- docs/source/apis/table.md
- misc/package/Data Files/MWSE/core/initialize.lua
- misc/package/Data Files/MWSE/core/meta/lib/table.lua
- `table.contains(tbl, value)` checks if a `valeu` is present in `tbl`.
- `table.equals(left, right)` recursively checks the (key, value) pairs of `left` and `right` to make sure they are the same.
> Add `table.contains` and `table.equals` functions.

- docs/source/guides/metadata.md
The metadata guide states that a lower `load-priority` results in a mod loading earlier. But this does not seem to be consistent with my testing. I have updated the page to state that a higher `load-priority` results in mods loading earlier.
The package sorting function (defined in `core/startLuaMods.lua`) has the code:
```lua
-- Then we sort by explicit load order.
if (a.load_priority ~= b.load_priority) then
return a.load_priority > b.load_priority
end
```
This results in mods with a higher `load_priority` being placed earlier in the `runtimes` array, resulting in them executing earlier.
To verify this, I created two mods, named `priority_5` and `priority_10`, with metadata files:
```toml
[package]
name = "Priority 10"
[tools.mwse]
lua-mod = "priority_10"
load-priority = 10
```
and …
> Docs: Fix typo regarding `load-priority` in the `metadata` guide

- autocomplete/definitions/global/table/removevalue.lua
- docs/source/apis/table.md
- misc/package/Data Files/MWSE/core/meta/lib/table.lua
My goal was to make it clearer that this function only works on array-style tables. But I can make this more explicit if desirable.
> Docs: Update description of `table.removevalue`

- misc/package/Data Files/MWSE/core/mcm/components/templates/Template.lua
If the MCM is closed and reopened, the most recently viewed page of a mods config menu will be displayed. If no previous page was viewed, then the first page is opened instead.
This is accomplished by just making the `Template:createSubcomponentsContainer` method call the already existing `clickTab` page instead of manually initializing the first page.
- This change was previously a part of #532, but I realized today that a more efficient implementation is possible by modifying the `mwseMCMTemplate` class itself. 
- The implementation in #532 would create the first page of a mods MCM and then click the most recently viewed tab. 
- The approach in this PR skips the creation of the first page, and only creates the most recently viewed page.
- This approach will remember the most recently …
> Make MCM Template reopen the last page

- misc/package/Data Files/MWSE/core/mcm/components/templates/Template.lua
The changes made in #610 resulted in `Template:clickTab` being called when `Template.elements.tabsBlock` might be `nil`. This could happen if the `Template` only had a single page.
This PR makes a small fix that adds a `nil` check to `Template:clickTab` to ensure `tabsBlock` is not `nil` before doing any `tabsBlock` related updates.
Note that while the actual change to the code is rather small, the git diff is a bit unpleasant because of the added indentation. If desired, this could be mitigated by instead doing something like
```lua
if not tabsBlock then
pageBlock:getTopLevelMenu():updateLayout()
return
end
```
Let me know if that would be better and I can make that change.
> Fix bug in `Template:clickTab`

- autocomplete/builders/common.lua
- autocomplete/builders/emmy.lua
- autocomplete/builders/mkdocs.lua
- docs/type-definitions-guide.md
For example, `tes3vector3.unitX` would could be documented as:
```lua
return {
type = "typeValue",
description = [[Creates a new vector pointing along the positive X axis.]],
valuetype = "tes3vector3",
}
```
Which would look like this on site:
> Docs: add support for type properties

- autocomplete/definitions/namedTypes/tes3ui.showMessageMenu.params.tooltip/callback.lua
- autocomplete/definitions/namedTypes/tes3ui.showMessageMenu.params.tooltip/header.lua
- autocomplete/definitions/namedTypes/tes3ui.showMessageMenu.params.tooltip/text.lua
- docs/source/types/tes3ui.showMessageMenu.params.tooltip.md
- misc/package/Data Files/MWSE/core/meta/class/tes3ui.showMessageMenu.params.tooltip.lua
None of the fields `callback`, `header`, `text` are required, this removes the incorrect `missing-fields` warning
> Docs: Fix fields in `tes3ui.showMessageMenu.params.tooltip` not marked optional

- MWSE/LuaCalcMovementSpeedEvent.cpp
It wasn't only the `calcWalkSpeed` event that had `type == 1`, but all of the [movement speed related](https://mwse.github.io/MWSE/events/calcFlySpeed/#related-events) events had the same problem. After this patch, they get their type set as indicated in the docs.
> Set m_Type in CalculateMovementSpeed constructor

- misc/package/Data Files/MWSE/core/i18n/eng.lua
- misc/package/Data Files/MWSE/core/mcm/components/templates/Template.lua
- misc/package/Data Files/MWSE/core/mcm/main.lua
This PR depends on #624, and it adds a universal keybinding menu to the MCM. This menu allows users to view and update the keybindings of all their mods in one place. This is something that C3pa have discussed adding in the past, and it [was recently requested by a user in the MWSE discord channel a few day ago](https://discord.com/channels/210394599246659585/381219559094616064/1402035124211810345).
Here are some screenshots of what the early prototype looks like:
- This PR should currently be viewed as a very early prototype/proof of concept of the feature. 
- The code changes are a bit messy, and the implementation still needs to be refined and thoroughly tested. 
- But I figured that for something like this, it would be best to make the PR early so that the implementation, …
> MCM: Add a universal keybinding menu.
